name: Add Reviewers new

on:
  pull_request:

env:
  USER_1: lhansamali
  USER_2: SongRaein

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prOwner = context.payload.pull_request.user.login;
            const reviewers = [];
            
            // Dynamically assign reviewers
            if (prOwner === process.env.USER_1) {
              reviewers.push(process.env.USER_2);
            } else if (prOwner === process.env.USER_2) {
              reviewers.push(process.env.USER_1);
            }

            if (reviewers.length > 0) {
              await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              });
              console.log(`Assigned reviewers: ${reviewers}`);
            } else {
              console.log('No reviewers assigned. PR owner does not match predefined users.');
            }
