name: 'Request Reviewers'

on:
  pull_request:
    types: ['opened', 'labeled', 'labeled']

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Request Reviewers
        uses: neo-diego-beltran/request-reviewers@f028375d516d93d6a4dd5f93feccfc7f3c768a9b
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config_path: ".github/request-reviewers.yml"
