  name: Reviewers

  on:
      pull_request_review:
      pull_request:
          types: [opened]

  jobs:
      reviewers:
          name: Reviewers
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@v2
              - uses: zattoo/reviewers@4.1.0
                with:
                    token: ${{secrets.TOKEN}}
                    source: '.reviewers.json'
                    path: '.github/workflows/reviewers.json'
