name: first
on:
  pull_request:
    types: [opened]
jobs:
  job1:
    name: First_job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v3
        
      - name: step two
        uses: andymckay/assign-reviewers@v1.0.1
        with:
          reviewers: |
            - SongRaein

      - name: step three
        run: echo "Added Reviewer"
