name: Assign Reviewers on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign reviewers
        uses: zattoo/reviewers@4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: main
          owners_path: ".github/workflows/reviewers.json"
          ignore: false
