name: first
on:
  pull_request:
    types: [opened]
jobs:
  job1:
    name: First_job
    runs-on: ubuntu-latest
    steps:   
      - name: step one
        uses: zattoo/reviewers@4.1.0
        with:
          reviewers: |    
            - SongRaein

      - name: step three
        run: echo "Added Reviewer"
