name: Add Reviewers

on:
  pull_request:

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Reviewer
        id: determine-reviewer
        run: |
          if [ "${{ github.actor }}" = "lhansamali" ]; then
            echo "reviewer=SongRaein" >> $GITHUB_ENV
          else
            echo "reviewer=lhansamali" >> $GITHUB_ENV
          fi

      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ env.reviewer }}
          re-request-when-approved: true
          re-request-when-changes-requested: true
